[project]
name = "WeClone"
version = "0.1.2"
description = ""
authors = [
    {name = "xming521"}
]
readme = "README.md"
requires-python = ">=3.9,<3.10"
dependencies = [
    "transformers==4.46.2",
    "llamafactory>=0.9.2",
    "pandas",
    "openai==0.28.0",
]

[project.optional-dependencies]
xcodec = ["xcodec2==0.1.3"]
wx = ["pywxdump"]
sparktts = [
    "einops>=0.8.1",
    "einx>=0.3.0",
    "numpy==1.26.4",
    "omegaconf>=2.3.0",
    "packaging>=24.2",
    "safetensors>=0.5.2",
    "soundfile>=0.12.1",
    "soxr>=0.5.0.post1",
    "torch>=2.5.1",
    "torchaudio>=2.5.1",
    "tqdm>=4.66.5",
    "transformers==4.46.2"
]

[dependency-groups]
xcodec = ["xcodec2==0.1.3"]
wx = ["pywxdump"]
sparktts = [
    "einops>=0.8.1",
    "einx>=0.3.0",
    "numpy==1.26.4",
    "omegaconf>=2.3.0",
    "packaging>=24.2",
    "safetensors>=0.5.2",
    "soundfile>=0.12.1",
    "soxr>=0.5.0.post1",
    "torch>=2.5.1",
    "torchaudio>=2.5.1",
    "tqdm>=4.66.5",
    "transformers==4.46.2"
]

[tool.uv]
conflicts = [
    [
      { group = "xcodec" },
      { group = "wx" },
      { group = "sparktts" },
    ],
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
default = true
